{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "piaware.fullname" . }}
  namespace: {{ include "piaware.namespace" . }}
  labels:
    {{- include "piaware.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: web
      protocol: TCP
    - name: beast
      port: {{ .Values.service.beastPort }}
      targetPort: beast
      protocol: TCP
    - name: basestation
      port: {{ .Values.service.baseStationPort }}
      targetPort: basestation
      protocol: TCP
    {{- if .Values.uat.receiverType }}
    - name: uat
      port: {{ .Values.service.uatPort }}
      targetPort: uat
      protocol: TCP
    {{- end }}
  selector:
    {{- include "piaware.selectorLabels" . | nindent 4 }}
{{- end }}
